services:
  app_proxy:
    environment:
      APP_HOST: pluto_frontend_1
      APP_PORT: 7777
    depends_on:
      - frontend
    restart: on-failure

  discovery:
    image: registry.gitlab.com/plutomining/pluto/pluto-discovery:1.0.3@sha256:dc2a5a642491748b20d1b2dddbba39f34b43afee4a3720739f1fe9fa42b4189a
    network_mode: "host"
    pid: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: on-failure
    environment:
      - PORT=7775
    volumes:
      - ${APP_DATA_DIR}/data/leveldb:/home/node/app/data
    user: "1000:1000"

  backend:
    image: registry.gitlab.com/plutomining/pluto/pluto-backend:1.0.3@sha256:82ac50f4f8a7c1c4e574c934ad1f7968f41304adc6b8ddbc27183802d6174981
    pid: host
    restart: on-failure
    environment:
      - PORT=7776
      - AUTO_LISTEN=true
      - DISCOVERY_SERVICE_HOST=http://172.17.0.1:7775
      - GF_HOST=http://pluto_grafana_1:3000
      - DELETE_DATA_ON_DEVICE_REMOVE=true
    volumes:
      - ${APP_DATA_DIR}/data/leveldb:/home/node/app/data
      - ${APP_DATA_DIR}/data/grafana:/home/node/app/grafana
    depends_on:
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy
    user: "1000:1000"

  frontend:
    image: registry.gitlab.com/plutomining/pluto/pluto-frontend:1.0.3@sha256:696a100592dc4f446612c6ba7549fd09094392d8b5c0860d3502a7bec30e40aa
    pid: host
    restart: on-failure
    depends_on:
      - backend
    environment:
      - PORT=7777
      - GF_HOST=http://pluto_grafana_1:3000
      - BACKEND_DESTINATION_HOST=http://pluto_backend_1:7776
    volumes:
      - ${APP_DATA_DIR}/umbrel-app.yml:/tmp/umbrel-app.yml:ro
    user: "1000:1000"

  prometheus:
    image: registry.gitlab.com/plutomining/pluto/pluto-prometheus:1.0.3@sha256:bb5fc20c6feacc374e12ca8611914d032969f6d873684ce6b35c533b6e92bf0e
    volumes:
      - ${APP_DATA_DIR}/data/prometheus:/prometheus
    pid: host
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget --spider --quiet http://localhost:9090/-/ready || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    user: "65534:65534"

  grafana:
    image: registry.gitlab.com/plutomining/pluto/pluto-grafana:1.0.3@sha256:1f6c3182b82c53328f9376afd77b6063249f25151f809d716b7265a4f295eefa
    pid: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${APP_PASSWORD}
      - GF_INSTALL_PLUGINS=marcusolsson-treemap-panel
    volumes:
      - ${APP_DATA_DIR}/data/grafana:/var/lib/grafana
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget --spider --quiet http://localhost:3000/api/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      prometheus:
        condition: service_healthy
    user: "472:472"
