services:
  app_proxy:
    environment:
      APP_HOST: pluto_frontend_1
      APP_PORT: 7777
    depends_on:
      - frontend
    restart: on-failure

  discovery:
    image: registry.gitlab.com/plutomining/pluto/pluto-discovery:1.0.1@sha256:79e04d0b1c3e49d4b1d221ba051c155f195017cd07594e9100e6bd196b1b0a52
    network_mode: "host"
    pid: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: on-failure
    environment:
      - PORT=7775
    volumes:
      - ${APP_DATA_DIR}/data/leveldb:/home/node/app/data
    user: "1000:1000"

  backend:
    image: registry.gitlab.com/plutomining/pluto/pluto-backend:1.0.1@sha256:53d30f0095d344ec26ad55cb55f8c1d5b2b83d354db9ea3a55a707584077f724
    pid: host
    restart: on-failure
    environment:
      - PORT=7776
      - AUTO_LISTEN=true
      - DISCOVERY_SERVICE_HOST=http://172.17.0.1:7775
      - GF_HOST=http://pluto_grafana_1:3000
      - DELETE_DATA_ON_DEVICE_REMOVE=true
    volumes:
      - ${APP_DATA_DIR}/data/leveldb:/home/node/app/data
      - ${APP_DATA_DIR}/data/grafana:/home/node/app/grafana
    depends_on:
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy
    user: "1000:1000"

  frontend:
    image: registry.gitlab.com/plutomining/pluto/pluto-frontend:1.0.1@sha256:ea6264d0bcefbfa40f5829ad14822fef2054b4ca42c8fff7bc9e1b5d2c8a983c
    pid: host
    restart: on-failure
    depends_on:
      - backend
    environment:
      - PORT=7777
      - GF_HOST=http://pluto_grafana_1:3000
      - BACKEND_DESTINATION_HOST=http://pluto_backend_1:7776
    volumes:
      - ${APP_DATA_DIR}/umbrel-app.yml:/tmp/umbrel-app.yml:ro
    user: "1000:1000"

  prometheus:
    image: registry.gitlab.com/plutomining/pluto/pluto-prometheus:1.0.1@sha256:2ed6bbd33757652a6f60de3f9cbebdb7653b37fce2d815cbc5b5ca430f39bd93
    volumes:
      - ${APP_DATA_DIR}/data/prometheus:/prometheus
    pid: host
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget --spider --quiet http://localhost:9090/-/ready || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    user: "65534:65534"

  grafana:
    image: registry.gitlab.com/plutomining/pluto/pluto-grafana:1.0.1@sha256:b3d10fa12276a9be3c7427aa9176d8ab5a6d2a020eda5dac78fd271406a20a8b
    pid: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${APP_PASSWORD}
      - GF_INSTALL_PLUGINS=marcusolsson-treemap-panel
    volumes:
      - ${APP_DATA_DIR}/data/grafana:/var/lib/grafana
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget --spider --quiet http://localhost:3000/api/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      prometheus:
        condition: service_healthy
    user: "472:472"
